const TOKEN = "TOKEN"
const TOKEN_SUCCESS = "TOKEN_SUCCESS"
const TOKEN_FAILS = "TOKEN_FAILS"

const CHATS = "CHATS"
const ADD_CHAT = "ADD_CHAT"
const CLEAR_CHATS = "CLEAR_CHATS"

export {
    TOKEN, TOKEN_SUCCESS, TOKEN_FAILS, CHATS, ADD_CHAT, CLEAR_CHATS
}